spring.application.name=disaster-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/disasterdb
spring.datasource.username=postgres
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=disasteralert-secret-key-256-bit-long-key-here
jwt.expiration=604800000
server.port=8081